data: 
  path: data/healthcare-dataset-stroke-data.csv
  test_size: 0.2
  random_state: 22520465
  target: stroke 
  number_features: 
    missing_values: mean # remove or mean or median or most_frequent
    log_transform: true # true or false
    features:
      - age
      - avg_glucose_level
      - bmi
      - hypertension
      - heart_disease
  categorical_features: 
    features: 
      - gender
      - ever_married
      - work_type
      - Residence_type
      - smoking_status
    encoding: one_hot # one_hot or label or target

train: 
  n_estimators: 500
  learning_rate: 0.1
  max_depth: 4
  gamma: 0
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 22520465
  objective: binary:logistic

